### ISSUE TITLE
Docstring missing for some functions using @_autogen_docstring

### ISSUE THREAD

**Issue by argentum2f** [davidhalter/jedi-vim#936]
### Issue

Docstring is missing for some functions, but not others even in the same module. In `matplotlib.pyplot` `pause()` shows full docstring, whereas `imshow()` does not. The thing in common that I've found seems to be that the functions that don't show the docstring (in vim-jedi) all have something like this in place of a docstring (right before the function):
`@_autogen_docstring(Axes.imshow)`

### Steps to reproduce
Create file, input
```
import matplotlib.pyplot as plt
plt.imshow()
plt.pause()
```
Put cursor over imshow, press K -> function definition only (no docstring)
Put cursor over pause, press K -> full docstring displayed

`pydoc matplotlib.pyplot.imshow`
does give full docstring.

##### Global Python

Using Python version 2 to access Jedi.
 - global sys.version: `2.7.5 (default, Jun 11 2019, 12:19:05), [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]`
 - global site module: `/usr/lib64/python2.7/site.pyc`

##### Jedi

 - path: `/home/*/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.pyc`
 - version: 0.14.1

##### Jedi environment: <SameEnvironment: 2.7.5 in /usr>

 - executable: /usr/bin/python
 - sys_path:
    - `/home/*/.local/lib/python2.7/site-packages/jedi-0.14.1-py2.7.egg`
    - `/home/*/.local/lib/python2.7/site-packages/parso-0.5.1-py2.7.egg`
    - `/home/*/.local/lib/python2.7/site-packages/pip-19.2.1-py2.7.egg`
    - `/usr/lib64/python27.zip`
    - `/usr/lib64/python2.7`
    - `/usr/lib64/python2.7/plat-linux2`
    - `/usr/lib64/python2.7/lib-tk`
    - `/usr/lib64/python2.7/lib-old`
    - `/usr/lib64/python2.7/lib-dynload`
    - `/home/*/.local/lib/python2.7/site-packages`
    - `/usr/lib64/python2.7/site-packages`
    - `/usr/lib64/python2.7/site-packages/gtk-2.0`
    - `/usr/lib/python2.7/site-packages`

##### Known environments

 - <Environment: 3.6.8 in /usr> (/usr/bin/python3.6)
 - <Environment: 2.7.5 in /usr> (/usr/bin/python2.7)

**Comment by davidhalter** [comment]
This might have been fixed on latest Jedi master. Pretty sure I fixed some docstring stuff in combination with decorators. Feel free to checkout the Jedi submodule to the latest master and let me know.

**Comment by argentum2f** [comment]
I'm not really sure how to do that. (I don't know that much about git). I tried:

```
git clone --recurse-submodules https://github.com/davidhalter/jedi-vim
cd jedi-vim/pythonx/jedi/
python setup.py install --user
```
(`--user` cause I don't jave root access)

Then ran vim again, but still have the same problem.

**Comment by davidhalter** [comment]
you don't need to install it. Just use `cd jedi-vim/pythonx/jedi/; git checkout master`.

**Comment by davidhalter** [comment]
Can you just check the latest release?
